import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import Container from "~/components/container";
import ThemeProvider from "~/provider/theme.provider";
import "~/styles/globals.css";

const font = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vevibe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Container>{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
